/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brandName?: string;
  tagline?: string;
  locations?: Array<{
    city?: string;
    addressLine?: string;
    hours?: string;
    phone?: string;
    _key: string;
  }>;
  instagram?: string;
  tiktok?: string;
  whatsapp?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  headline?: string;
  story?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  certifications?: Array<string>;
  yearsExperience?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type GalleryItem = {
  _id: string;
  _type: "galleryItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  category?: "lashes" | "brows" | "pmu" | "makeup" | "facial";
  before?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  after?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  consent?: boolean;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  text?: string;
  rating?: 1 | 2 | 3 | 4 | 5;
  serviceCategory?: string;
  featured?: boolean;
};

export type Training = {
  _id: string;
  _type: "training";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  level?: "Einsteiger" | "Fortgeschritten" | "Masterclass";
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  durationDays?: number;
  price?: number;
  includes?: Array<string>;
  upcomingDates?: Array<{
    date?: string;
    location?: "Bruchsal" | "J\xFClich" | "Online";
    spotsLeft?: number;
    _key: string;
  }>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  seoTitle?: string;
  seoDescription?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?: "lashes" | "brows" | "pmu" | "makeup" | "facial";
  shortDescription?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  duration?: number;
  priceFrom?: number;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  calcomEventType?: string;
  seoTitle?: string;
  seoDescription?: string;
  order?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SiteSettings
  | SanityImageAssetReference
  | About
  | SanityImageCrop
  | SanityImageHotspot
  | GalleryItem
  | Testimonial
  | Training
  | Slug
  | Service
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: app/galerie/page.tsx
// Variable: GALLERY_QUERY
// Query: *[_type == "galleryItem" && consent == true] | order(_createdAt desc) {    _id, title, category, before, after  }
export type GALLERY_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  category: "brows" | "facial" | "lashes" | "makeup" | "pmu" | null;
  before: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  after: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: app/kontakt/page.tsx
// Variable: SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0] {    brandName, tagline, whatsapp, instagram,    locations[]{city, addressLine, hours, phone}  }
export type SETTINGS_QUERY_RESULT = {
  brandName: string | null;
  tagline: string | null;
  whatsapp: string | null;
  instagram: string | null;
  locations: Array<{
    city: string | null;
    addressLine: string | null;
    hours: string | null;
    phone: string | null;
  }> | null;
} | null;

// Source: app/leistungen/[slug]/page.tsx
// Variable: SERVICE_QUERY
// Query: *[_type == "service" && slug.current == $slug][0] {    _id, title, "slug": slug.current, category, shortDescription, description,    priceFrom, duration, image, gallery, calcomEventType, seoTitle, seoDescription  }
export type SERVICE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  category: "brows" | "facial" | "lashes" | "makeup" | "pmu" | null;
  shortDescription: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  priceFrom: number | null;
  duration: number | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  gallery: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  calcomEventType: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
} | null;

// Source: app/leistungen/[slug]/page.tsx
// Variable: ALL_SLUGS_QUERY
// Query: *[_type == "service"] { "slug": slug.current }
export type ALL_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: app/leistungen/page.tsx
// Variable: SERVICES_QUERY
// Query: *[_type == "service"] | order(order asc) {    _id, title, "slug": slug.current, category, shortDescription, priceFrom, duration, image  }
export type SERVICES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  category: "brows" | "facial" | "lashes" | "makeup" | "pmu" | null;
  shortDescription: string | null;
  priceFrom: number | null;
  duration: number | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: app/schulungen/[slug]/page.tsx
// Variable: TRAINING_QUERY
// Query: *[_type == "training" && slug.current == $slug][0] {    _id, title, "slug": slug.current, level, description, durationDays, price,    includes, upcomingDates[]{date, location, spotsLeft}, image, seoTitle, seoDescription  }
export type TRAINING_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  level: "Einsteiger" | "Fortgeschritten" | "Masterclass" | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  durationDays: number | null;
  price: number | null;
  includes: Array<string> | null;
  upcomingDates: Array<{
    date: string | null;
    location: "Bruchsal" | "J\xFClich" | "Online" | null;
    spotsLeft: number | null;
  }> | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  seoTitle: string | null;
  seoDescription: string | null;
} | null;

// Source: app/schulungen/[slug]/page.tsx
// Variable: ALL_TRAINING_SLUGS_QUERY
// Query: *[_type == "training"] { "slug": slug.current }
export type ALL_TRAINING_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: app/schulungen/page.tsx
// Variable: TRAININGS_QUERY
// Query: *[_type == "training"] | order(title asc) {    _id, title, "slug": slug.current, level, durationDays, price, image,    "upcomingDates": upcomingDates[]{date, location, spotsLeft}  }
export type TRAININGS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  level: "Einsteiger" | "Fortgeschritten" | "Masterclass" | null;
  durationDays: number | null;
  price: number | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  upcomingDates: Array<{
    date: string | null;
    location: "Bruchsal" | "J\xFClich" | "Online" | null;
    spotsLeft: number | null;
  }> | null;
}>;

// Source: app/ueber-mich/page.tsx
// Variable: ABOUT_QUERY
// Query: *[_type == "about"][0] {    _id, heroImage, headline, story, certifications, yearsExperience  }
export type ABOUT_QUERY_RESULT = {
  _id: string;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  headline: string | null;
  story: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  certifications: Array<string> | null;
  yearsExperience: number | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "galleryItem" && consent == true] | order(_createdAt desc) {\n    _id, title, category, before, after\n  }\n': GALLERY_QUERY_RESULT;
    '\n  *[_type == "siteSettings"][0] {\n    brandName, tagline, whatsapp, instagram,\n    locations[]{city, addressLine, hours, phone}\n  }\n': SETTINGS_QUERY_RESULT;
    '\n  *[_type == "service" && slug.current == $slug][0] {\n    _id, title, "slug": slug.current, category, shortDescription, description,\n    priceFrom, duration, image, gallery, calcomEventType, seoTitle, seoDescription\n  }\n': SERVICE_QUERY_RESULT;
    '*[_type == "service"] { "slug": slug.current }': ALL_SLUGS_QUERY_RESULT;
    '\n  *[_type == "service"] | order(order asc) {\n    _id, title, "slug": slug.current, category, shortDescription, priceFrom, duration, image\n  }\n': SERVICES_QUERY_RESULT;
    '\n  *[_type == "training" && slug.current == $slug][0] {\n    _id, title, "slug": slug.current, level, description, durationDays, price,\n    includes, upcomingDates[]{date, location, spotsLeft}, image, seoTitle, seoDescription\n  }\n': TRAINING_QUERY_RESULT;
    '*[_type == "training"] { "slug": slug.current }': ALL_TRAINING_SLUGS_QUERY_RESULT;
    '\n  *[_type == "training"] | order(title asc) {\n    _id, title, "slug": slug.current, level, durationDays, price, image,\n    "upcomingDates": upcomingDates[]{date, location, spotsLeft}\n  }\n': TRAININGS_QUERY_RESULT;
    '\n  *[_type == "about"][0] {\n    _id, heroImage, headline, story, certifications, yearsExperience\n  }\n': ABOUT_QUERY_RESULT;
  }
}
